services:
  mongodb:
    image: mongo:8
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 2s
      timeout: 20s
      retries: 10
    env_file:
      - ./configuration/mongodb.env
    volumes:
      - ${MONGODB_DATA_PATH}:/data/db

  redis:
    image: redis:latest
    healthcheck:
      test: "redis-cli ping"
      interval: 2s
      timeout: 20s
      retries: 10
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    environment:
      - APP_HTTP_HOST=0.0.0.0
      - APP_HTTP_PORT=80
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - APP_COMPONENT=fastapi
    env_file:
      - ./configuration/app.env
      - ./configuration/aws.env
      - ./configuration/mongodb.env
      - ./configuration/redis.env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "curl --fail http://localhost/api/v1/health/"
      interval: 10s
      timeout: 1s
      retries: 2
